apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: thisisaarush/order-service:latest
          ports:
            - containerPort: 5003
          env:
            - name: MONGO_URI
              value: "mongodb://admin:password@mongo-0.mongo.default.svc.cluster.local:27017/orders?authSource=admin"
            - name: PRODUCT_SERVICE_URI
              value: "http://product-service.default.svc.cluster.local:5001"
            - name: NOTIFICATION_SERVICE_URI
              value: "http://notification-service.default.svc.cluster.local:5005"
            - name: USER_SERVICE_URI
              value: "http://user-service.default.svc.cluster.local:5000"
          livenessProbe:
            httpGet:
              path: /api/orders
              port: 5003
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/orders
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
